GET http://localhost:8002/business/hello
Accept: application/json

###

GET http://localhost:8008/business/hello
Accept: application/json

###

GET http://localhost:8008/business/admin/train/gen-seat/G1
Accept: application/json

###

