GET http://localhost:8001/member/hello
Accept: application/json
###

GET http://localhost:8008/member/hello
Accept: application/json
###

GET http://localhost:8008/member/member/count
Accept: application/json
###

POST http://localhost:8008/member/member/register?mobile=18845878708
Accept: application/json
###