POST http://localhost:8008/member/passenger/save
Content-Type: application/json
token:{{token}}

{
  "name":"test",
  "idCard":"6",
  "type": "1"
}

###

GET http://localhost:8008/member/passenger/query-list?page=1&size=4
Accept: application/json
token: {{token}}

###